apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce-app.fullname" . }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ecommerce-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ecommerce-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ecommerce-app.serviceAccountName" . }}
      containers:
        - name: ecommerce-app
          image: "rudhra378/ecommerce-app:latest"
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          env:
            - name: DB_HOST
              value: postgres-service

            - name: DB_PORT
              value: "5432"

            - name: DB_USER
              value: postgres

            - name: DB_PASSWORD
              value: postgres

            - name: DB_NAME
              value: ecommerce

            - name: JWT_SECRET
              value: mysecretkey

          livenessProbe:
            httpGet:
              path: /health
              port: http

          readinessProbe:
            httpGet:
              path: /health
              port: http